<?php

const DENTISTAS = "DENTISTAS";
const DENTISTA_ID = "DENTISTA_ID";
const NOMBRE = "NOMBRE";
const APELLIDO_P = "APELLIDO_P";
const APELLIDO_M = "APELLIDO_M";
const CEDULA = "CEDULA";
const ESPECIALIDAD = "ESPECIALIDAD";
const TELEFONO = "TELEFONO";
const DESCRIPCION = "DESCRIPCION";
const USUARIO = "USUARIO";
const CORREO = "CORREO";
const CONTRASENA = "CONTRASENA";
